#!/usr/bin/env python3
"""Extract the deck's text to markdown, for pasting where a file cannot go.

    python scripts/dump_deck_text.py

The submission portal, and most forms like it, want content rather than an attachment. Copying
slides by hand into a document is how the two versions start disagreeing - which is the same failure
this project already fixed for the results tables and the configuration block. So the extract is
generated from the .pptx itself and regenerated rather than edited.

Shapes are emitted top-to-bottom, then left-to-right, so the text reads in the order the eye takes
the slide rather than in the order PowerPoint happens to store the shapes.
"""

from __future__ import annotations

import sys
from pathlib import Path

from pptx import Presentation

REPO_ROOT = Path(__file__).resolve().parents[1]
DECK = REPO_ROOT / "Silli-Con Artists_PS02.pptx"
OUTPUT = REPO_ROOT / "docs" / "DECK_CONTENTS.md"

#: The problem statement's mapping, which is what the slides are graded against.
TITLES = ["Team Details", "Problem Statement Addressed", "Idea Description",
          "Proposed Solution", "Innovation and Uniqueness", "Results",
          "Technology & Feasibility", "GitHub & Video Link", "References"]

#: One row of the shape grid, in EMU. Shapes within this of each other count as the same line, so
#: a stat and its caption do not get separated by a rounding difference of a few thousandths.
ROW_TOLERANCE = 91_440


def main() -> int:
    if not DECK.exists():
        print(f"error: {DECK.name} not found - run scripts/make_submission_deck.py first",
              file=sys.stderr)
        return 2

    prs = Presentation(str(DECK))
    lines = [
        "# Deck contents — Silli-Con Artists, PS 02 (Drift-Sense)",
        "",
        f"Plain-text extract of `{DECK.name}`, for pasting into the submission portal or any form",
        "that wants the content rather than the file.",
        "",
        "**Generated by `scripts/dump_deck_text.py` — regenerate rather than editing**, so this",
        "cannot drift from the deck the way a hand-copied version would.",
        "",
    ]
    for index, slide in enumerate(prs.slides):
        title = TITLES[index] if index < len(TITLES) else f"Slide {index + 1}"
        lines += [f"## Slide {index + 1} — {title}", ""]
        shapes = [s for s in slide.shapes
                  if s.has_text_frame and s.text_frame.text.strip() and s.top is not None]
        for shape in sorted(shapes, key=lambda s: (round(s.top / ROW_TOLERANCE), s.left)):
            for line in shape.text_frame.text.splitlines():
                if line.strip():
                    lines.append(line.strip())
            lines.append("")
        lines.append("")

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"  Wrote {OUTPUT.relative_to(REPO_ROOT).as_posix()} "
          f"({len(prs.slides._sldIdLst)} slides)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
